### ISSUE TITLE
Error message from SLB / hope you can help me

### ISSUE THREAD

**Issue by Seaver06** [SickSkillz/SuperLuckyBlock#1]
7.08 18:22:07 [Server] INFO ... 15 more
17.08 18:22:07 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO at me.ghostrider.superluckyblock.commands.SLBCommandExecutor.onCommand(SLBCommandExecutor.java:131) ~[?:?]
17.08 18:22:07 [Server] INFO at me.ghostrider.superluckyblock.utils.GeneralUtils.colorText(GeneralUtils.java:16) ~[?:?]
17.08 18:22:07 [Server] INFO at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO Caused by: java.lang.NullPointerException
17.08 18:22:07 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
17.08 18:22:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
17.08 18:22:07 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
17.08 18:22:07 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.jar:git-Spigot-7228328-50b75cd]
17.08 18:22:07 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'slb' in plugin SuperLuckyBlock v2.11

**Comment by SickSkillz** [comment]
Hello,

Thanks for reporting this issue!
I will try and fix it as soon as possible.
If I need any more information I will let you know ;)

- Danny
