### ISSUE TITLE
Howdy!

### ISSUE THREAD

**Issue by JohnBeres1** [SickSkillz/SuperLuckyBlock#2]

**Comment by JohnBeres1** [comment]
Can you take a look at the chance to spawn while mining? I lowered it below 1% and my players are still getting them much too often. I was honestly hoping for like 1 in every 1000 blocks or so...

**Comment by SickSkillz** [comment]
Hello JohnBeres1,

I have changed it a bit in the latest update and I have added a timeout. I hope this fixed your problem.

- SickSkillz
