### ISSUE TITLE
Give player LuckyBlock from console wrong message.

### ISSUE THREAD

**Issue by VergilPrime** [SickSkillz/SuperLuckyBlock#6]
https://i.imgur.com/RwicUwn.png

Tried running "slb give 1 VergilPrime" in console.

Message returned in console: "SLB >> CONSOLE gave you a luckyblock."

VergilPrime did receive a luckyblock, but no message.

**Comment by SickSkillz** [comment]
Hello VergilPrime,
Thanks for reporting this issue!
I will look into it as soon as I am able to.

**Comment by SickSkillz** [comment]
Fixed in version 2.6.3
